### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by dextermallo** [coreruleset/rules-performance-tests#2]
The issue is the project roadmap for rules-performance-tests (sorted by priority - High to Low ):

## On-going

- [x] [Fix/Feat] Fix/update the unit test (currently 44%, goals ≥ 75% coverage)
- [ ] [Chore] update documentation (for thresholds, integrations, etc.)
- [ ] [Dev] Add markdown for contribution/security
- [x] [Dev] Add a way that people can see the demo for pipeline mode
- [ ] [Feat] Add Unit test into GitHub Action

## To-dos

- [ ] [Feat] Use a custom CLI name instead of `poetry run collect` and `poetry run report`
- [ ] [Feat] Fine-tune/add new args for commands, such as removing temporary files after running the commands.
- [ ] [Fix/Feat] The implemented utils (go-ftw, cAdvisor, and locust) have several items that can be improved. For instance, locust runs N requests within 60 seconds, and M test cases share these requests. Specifically, some test cases might be run insufficiently.
- [ ] [Feat] Add visualization reports (image-based)
- [ ] [Feat] Add visualization reports (HTML-based) to support pipeline mode output
- [ ] [Feat] Threshold is designed for the pipeline. The summary should be able to show as a comment in the PR.
- [ ] [Feat] Add eBPF and other utils

## Ideas

- Is there any library that can test "regex" performance?
